name: Profile assets

on:
  schedule:
    - cron: "0 3 * * *"   # 1x/dia
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate snake SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: alancampos-ai
          outputs: |
            assets/github-snake-dark.svg?palette=github-dark
            assets/github-snake-light.svg?palette=github-light

      - name: Commit changes
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: update snake" || echo "no changes"
          git push
