name: profile-assets

on:
  schedule:
    - cron: "* */12 * * *"  # a cada 12h
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - name: Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: alancampos-ai
          outputs: dist/github-contribution-grid-snake.svg

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
