name: profile-assets

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

permissions:
  contents: write

concurrency:
  group: publish-assets
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Gera SVGs e GIFs (claro e escuro)
      - name: Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/snake.svg?color_snake=blue
            assets/snake-dark.svg?palette=github-dark&color_snake=blue
            assets/snake.gif?color_snake=blue
            assets/snake-dark.gif?palette=github-dark&color_snake=blue

      # Commit somente dos assets gerados
      - name: Commit assets
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update profile assets (svg+gif)"
          file_pattern: |
            assets/*.svg
            assets/*.gif
