name: profile-assets

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"  # 03:00 UTC ≈ 00:00 America/Sao_Paulo

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    # ajuste se seu branch padrão não for "main"
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Preparar diretório de saída
        shell: bash
        run: |
          set -Eeuo pipefail
          mkdir -p assets

      - name: Snake (azul)
        id: snake
        uses: Platane/snk@v3
        continue-on-error: true
        with:
          github_user_name: ${{ github.repository_owner }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: |
            assets/snake.svg?color_snake=blue
            assets/snake-dark.svg?palette=github-dark&color_snake=blue

      - name: Fallback do snake se offline
        shell: bash
        run: |
          set -Eeuo pipefail
          for f in snake.svg snake-dark.svg; do
            if [ ! -s "assets/$f" ]; then
              printf '%s\n' "<svg xmlns='http://www.w3.org/2000/svg' width='600' height='40'><text x='10' y='25' font-size='16'>$f placeholder</text></svg>" > "assets/$f"
            fi
          done

      - name: Sanidade dos SVGs
        shell: bash
        run: |
          set -Eeuo pipefail
          for f in assets/snake.svg assets/snake-dark.svg; do
            test -s "$f"
          done
          ls -l assets

      - name: Publicar artifacts
        uses: actions/upload-artifact@v4
        with:
          name: profile-assets-${{ github.run_id }}
          path: assets/*.svg
          retention-days: 7

      # Em vez de push direto no main, abre/atualiza um PR fixo
      - name: Abrir/atualizar PR com os SVGs
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update profile snake"
          title: "chore: update profile snake"
          body: "Atualização automática dos assets do perfil."
          branch: bot/update-snake
          add-paths: |
            assets/snake.svg
            assets/snake-dark.svg
