# .github/workflows/profile-assets.yml
name: profile-assets

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"   # 1x/dia

permissions:
  contents: write

concurrency:
  group: publish-assets
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Snake (azul)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/snake.svg?color_snake=blue
            assets/snake-dark.svg?palette=github-dark&color_snake=blue

      # Reescreve APENAS as 3 URLs do bloco para RAW + cache-bust
      - name: Fix links da animação para RAW + cache-bust
        run: |
          set -euo pipefail
          run_id="${{ github.run_id }}"
          RAW_BASE="https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/main/assets"
          perl -0777 -pe "s#(?:\./)?assets/snake-dark\.svg(?:\?[^\"')]+)?#${RAW_BASE}/snake-dark.svg?v=${run_id}#g; s#(?:\./)?assets/snake\.svg(?:\?[^\"')]+)?#${RAW_BASE}/snake.svg?v=${run_id}#g" -i README.md

      - name: Commit no main
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update profile assets (raw links + cache-bust)"
          file_pattern: |
            assets/*.svg
            README.md
