name: profile-assets

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

permissions:
  contents: write

jobs:
  build:
    if: ${{ github.ref_name == github.event.repository.default_branch }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Preparar diretório
        run: mkdir -p assets

      - name: Gerar SVGs da cobrinha azul (LNCC)
        uses: Platane/snk@v3
        with:
          github_user_name: alancampos-ai
          outputs: |
            assets/snake.svg?color_snake=%230057d8
            assets/snake-dark.svg?palette=github-dark&color_snake=%230057d8

      - name: Cache-bust por conteúdo (força ETag novo)
        run: |
          TS=$(date -u +%Y%m%d%H%M%S)
          for f in assets/snake.svg assets/snake-dark.svg; do
            [ -s "$f" ] || continue
            awk -v ts="$TS" 'NR==1 && /<svg/ { sub(/<svg/, "<svg data-build=\"" ts "\"") } { print }' "$f" > "$f.tmp" && mv "$f.tmp" "$f"
          done

      - name: Commit automático
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update profile snake (blue + cache-bust)"
          file_pattern: assets/*.svg
