name: profile-assets

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"  # 03:00 UTC ≈ 00:00 America/Sao_Paulo

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Preparar diretório de saída
        run: mkdir -p assets

      - name: Gerar snake (azul)
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: |
            assets/snake.svg?color_snake=blue
            assets/snake-dark.svg?palette=github-dark&color_snake=blue

      - name: Sanidade dos SVGs
        run: |
          set -e
          test -s assets/snake.svg
          test -s assets/snake-dark.svg
          ls -lh assets

      - name: Cache-busting no README
        run: |
          ts="$(date -u +%Y%m%d%H%M%S)"
          sed -i -E "s#(assets/snake-dark\.svg)(\?v=[0-9]+)?#\1?v=${ts}#g" README.md
          sed -i -E "s#(assets/snake\.svg)(\?v=[0-9]+)?#\1?v=${ts}#g" README.md

      - name: Commit automático
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: refresh snake"
          file_pattern: |
            assets/snake*.svg
            README.md
