name: profile-assets

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: ${{ github.ref_name == github.event.repository.default_branch }}
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Preparar diretório
        run: mkdir -p assets

      - name: Gerar SVGs da cobrinha azul
        uses: Platane/snk@v3
        continue-on-error: true
        with:
          github_user_name: alancampos-ai
          github_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: |
            assets/snake.svg?color_snake=%230057d8
            assets/snake-dark.svg?palette=github-dark&color_snake=%230057d8

      - name: Fallback se geração falhar
        run: |
          for f in snake.svg snake-dark.svg; do
            if [ ! -s "assets/$f" ]; then
              printf '%s\n' "<svg xmlns='http://www.w3.org/2000/svg' width='640' height='40'><text x='10' y='26' font-size='16' font-family='monospace'>$f placeholder</text></svg>" > "assets/$f"
            fi
          done

      - name: Sanidade
        run: |
          test -s assets/snake.svg
          test -s assets/snake-dark.svg

      - name: Commit automático
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update profile snake (blue)"
          file_pattern: assets/*.svg
