name: profile-assets

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"  # 03:00 UTC ≈ 00:00 América/São_Paulo (BRT, sem DST)

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Preparar diretório de saída
        shell: bash
        run: |
          set -Eeuo pipefail
          mkdir -p assets

      - name: Snake (azul)
        id: snake
        uses: Platane/snk@v3
        continue-on-error: true
        with:
          github_user_name: ${{ github.repository_owner }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: |
            assets/snake.svg?color_snake=blue
            assets/snake-dark.svg?palette=github-dark&color_snake=blue

      - name: Fallback do snake se offline
        shell: bash
        run: |
          set -Eeuo pipefail
          for f in snake.svg snake-dark.svg; do
            if [ ! -s "assets/$f" ]; then
              printf '%s\n' "<svg xmlns='http://www.w3.org/2000/svg' width='600' height='40'><text x='10' y='25' font-size='16'>$f placeholder</text></svg>" > "assets/$f"
            fi
          done

      - name: Stats e Top Langs (com placeholders)
        shell: bash
        run: |
          set -Eeuo pipefail
          IFS=$'\n\t'
          curl_opts=(--fail --silent --show-error --location --max-time 20 --retry 3 --retry-delay 2)
          curl "${curl_opts[@]}" "https://github-readme-stats.vercel.app/api?username=${GITHUB_REPOSITORY_OWNER}&show_icons=true&include_all_commits=true&count_private=true&disable_animations=false&theme=transparent" -o assets/stats.svg \
            || printf '%s\n' '<svg xmlns="http://www.w3.org/2000/svg" width="600" height="40"><text x="10" y="25" font-size="16">stats.svg placeholder</text></svg>' > assets/stats.svg
          curl "${curl_opts[@]}" "https://github-readme-stats.vercel.app/api/top-langs/?username=${GITHUB_REPOSITORY_OWNER}&layout=compact&langs_count=10&theme=transparent" -o assets/toplangs.svg \
            || printf '%s\n' '<svg xmlns="http://www.w3.org/2000/svg" width="600" height="40"><text x="10" y="25" font-size="16">toplangs.svg placeholder</text></svg>' > assets/toplangs.svg

      - name: Sanidade dos SVGs
        shell: bash
        run: |
          set -Eeuo pipefail
          for f in assets/snake.svg assets/snake-dark.svg assets/stats.svg assets/toplangs.svg; do
            test -s "$f"
          done
          ls -l assets

      - name: Cache-bust automático no README
        shell: bash
        run: |
          set -Eeuo pipefail
          run_id="${{ github.run_id }}"
          if [ -f README.md ]; then
            sed -E -i \
              -e "s#(\./)?assets/snake(-dark)?\.svg(\?v=[^\"')]+)?#assets/snake\2.svg?v=${run_id}#g" \
              -e "s#(\./)?assets/stats\.svg(\?v=[^\"')]+)?#assets/stats.svg?v=${run_id}#g" \
              -e "s#(\./)?assets/toplangs\.svg(\?v=[^\"')]+)?#assets/toplangs.svg?v=${run_id}#g" \
              README.md
          fi

      - name: Commit no main
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update profile assets (+cache-bust)"
          file_pattern: |
            assets/*.svg
            README.md
          branch: ${{ github.ref_name }}
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
