name: Refresh README cards

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  snapshot:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - run: mkdir -p assets
      - name: Download cards
        run: |
          TS=$(date -u +%s)
          curl -sL "https://github-readme-stats.vercel.app/api?username=alancampos-ai&show_icons=true&include_all_commits=true&rank_icon=percentile&number_format=short&hide_border=true&theme=transparent&locale=en&ts=$TS" -o assets/stats.svg
          curl -sL "https://github-readme-stats.vercel.app/api/top-langs/?username=alancampos-ai&layout=compact&langs_count=8&card_width=320&hide_border=true&theme=transparent&locale=en&ts=$TS" -o assets/toplangs.svg
      - name: Commit
        run: |
          if [[ -n "$(git status --porcelain assets)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add assets/stats.svg assets/toplangs.svg
            git commit -m "chore(readme): refresh cards [skip ci]"
            git push
          fi
