git clone https://github.com/alancampos-ai/alancampos-ai.git
cd alancampos-ai
mkdir -p .github/workflows
cat > .github/workflows/snake.yml <<'YAML'
name: snake
on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Gerar animações
        uses: Platane/snk@v3
        with:
          github_user_name: alancampos-ai
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
      - name: Publicar no branch output
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
YAML
git add .github/workflows/snake.yml
git commit -m "add snake workflow"
git push origin main
