name: snake

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 3 * * *"     # 03:00 UTC (≈ 00:00 em America/Sao_Paulo) 
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gerar animações
        uses: Platane/snk@v3
        with:
          github_user_name: alancampos-ai
          outputs: |
            dist/snake.svg?color_snake=%231e90ff
            dist/snake-dark.svg?palette=github-dark&color_snake=%231e90ff

      - name: Publicar no branch output
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
